services:
  opensmtpd:
    image: opensmtpd
    container_name: opensmtpd
    restart: always
    ports:
      - 25:25
      - 465:465
      - 587:587
    environment:
      - TZ=America/Chicago
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
      - ./smtpd.conf:/etc/smtpd.conf:ro
      - ./supervisord.conf:/etc/supervisor/supervisord.conf:ro

