services:
  opensmtpd:
    image: opensmtpd
    container_name: opensmtpd
    restart: always
    ports:
      - 25:25
      - 465:465
      - 587:587
    environment:
      - TZ=America/Chicago
    volumes:
      - ./smtpd.conf:/etc/smtpd.conf:ro
      - ./supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./allowed_hosts:/etc/mail_allowed_hosts:ro
      - ./logs:/var/log/smtpd:ro

