services:
  opensmtpd:
    image: ghcr.io/cody-chapman/opensmtpd:latest
    container_name: opensmtpd
    restart: always
    ports:
      - 25:25
      - 465:465
      - 587:587
      - 8080:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - ./smtpd.conf:/etc/smtpd.conf:ro
      - ./supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./allowed_hosts:/etc/mail_allowed_hosts:ro
      - ./logs:/var/log/opensmtpd
      - ./smtpd-manage:/app/amtpd-manage
      - ./tailog.ps1:/app/tailog.ps1

