# Global directives
$ModLoad imuxsock
$ModLoad imjournal
$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_FileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging off

# Set proper permissions for log files
$FileOwner root
$FileGroup root
$FileCreateMode 0644

# Log all mail related messages to a dedicated file
:programname, isequal, "smtpd" /var/log/openmtpd/mail.log
:programname, isequal, "smtpd" ~

# Log to console (for docker logs)
*.info;mail.none;authpriv.none;cron.none /dev/console

# Default logging
*.emerg :omusrmsg:*
daemon.*;mail.*;authpriv.*;cron.* ~
