# Listen for local connections only
listen on 0.0.0.o

# Define the relay action
# M365 uses STARTTLS on port 587
action "relay_o365" relay \
    host smtp://smtp.office365.com:25 

# Match all outgoing mail and send it via the O365 action
match for any action "relay_o365"
