[supervisord]
nodaemon=true
minfds=1024
minprocs=200
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true
nocleanup=true
user=root
directory=/tmp
umask=022
strip_ansi=false

[program:rsyslog]
command=/usr/sbin/rsyslogd -n -c 2
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/rsyslog.log
stderr_logfile=/var/log/rsyslog.err.log

[program:opensmtpd]
command=/usr/sbin/smtpd -d
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/openmtpd.log
stderr_logfile=/var/log/openmtpd.err.log
