[supervisord]
nodaemon=true
minfds=1024
minprocs=200
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true
nocleanup=true
user=root
directory=/tmp
umask=022
strip_ansi=false

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:opensmtpd]
command=/usr/sbin/smtpd -d
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/opensmtpd/opensmtpd.log
stderr_logfile=/var/log/opensmtpd/opensmtpd.log
priority=10
; Log Rolling Logic
stdout_logfile_maxbytes=40MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=40MB
stderr_logfile_backups=10

[program:powershell]
# Use -NoProfile to speed up startup and -Command or -File for the script
# We add "unbuffered" logic by ensuring stdout/stderr are redirected
command=/usr/bin/pwsh -NoProfile -NonInteractive -File "/app/tailog.ps1"
user=root
autostart=true
autorestart=true
# Use 'environment' to pass variables that loop.ps1 can read via $env:VAR_NAME
environment=PSExecutionPolicyPreference='Bypass'
stdout_logfile=/var/log/opensmtpd/pwsh.log
stdout_logfile_maxbytes=40MB
stdout_logfile_backups=10
stderr_logfile=/var/log/opensmtpd/pwsh.log
stderr_logfile_maxbytes=40MB
stderr_logfile_backups=10
