[supervisord]
nodaemon=true
minfds=1024
minprocs=200
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true
nocleanup=true
user=root
directory=/tmp
umask=022
strip_ansi=false

[program:opensmtpd]
command=/usr/sbin/smtpd -d
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/opensmtpd.log
stderr_logfile=/var/log/opensmtpd.err.log
priority=10
; Log Rolling Logic
stdout_logfile_maxbytes=40MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=40MB
stderr_logfile_backups=10
